### ISSUE TITLE
Elasticsearch returns 200 on permission error

### ISSUE THREAD

**Issue by dmnfortytwo** [opendistro-for-elasticsearch/security#217]
Hi. I have an ES cluster with opendistro and fluentd writing into it. I reconfigured permissions for fluentd user to use logstash role, but this role does not allow index creation thus nothing is written into ES, but it returns 200 OK and data get lost.

ES log:
```
[2020-01-29T12:34:10,026][INFO ][c.a.o.s.p.PrivilegesEvaluator] [elasticsearch-gce-be-1] No index-level perm match for User [name=td-agent, backend_roles=[], requestedTenant=null] Resolved [aliases=[], indices=[techops_logs--2020.01.29], allIndices=[techops_logs--2020.01.29], types=[*], originalRequested=[techops_logs--2020.01.29], remoteIndices=[]] [Action [indices:admin/create]] [RolesChecked [logstash, own_index]]
[2020-01-29T12:34:10,026][INFO ][c.a.o.s.p.PrivilegesEvaluator] [elasticsearch-gce-be-1] No permissions for [indices:admin/create]
```

fluentd log:
`2020-01-29 12:34:09 +0000 [info]: #0 POST https://td-agent:****@elasticsearch-gce-be-1-prod:9200/_bulk [status:200, request:0.013s, query:0.000s]`

```
elasticsearch-oss 7.3.2
opendistro-alerting 1.3.0.1-1
opendistro-index-management 1.3.0.1-1
opendistro-job-scheduler 1.3.0.0-1
opendistro-performance-analyzer 1.3.0.0-1
opendistro-security 1.3.0.0-0
opendistro-sql 1.3.0.0-1
opendistroforelasticsearch 1.3.0-1
```

**Comment by palashhedau** [comment]
Hi Apologies for the late response.

I tried reproducing your error, it looks like a valid error but gives 200. 
But in actual response data, it has the permission error code. 

{"took":9,"errors":true,"items":[{"index":{"_index":"test_data","_type":"_doc","_id":"1","status":403,"error":{"type":"security_exception","reason":"no permissions for [indices:admin/create] and User [name=logstash_user, backend_roles=[captains, starfleet], requestedTenant=null]"}}}]}

Let me know if you can use this? Resolving as of now. Please reopen if otherwise.

**Comment by dmnfortytwo** [comment]
This is definitely incorrect behavior.
Having permission error as a result of request shouldn't not produce 200 OK response, just because request failed.

**Comment by dmnfortytwo** [comment]
I don't have permission to reopen issue.
