### ISSUE TITLE
role to role mapping not working 

### ISSUE THREAD

**Issue by NicoP-S** [opendistro-for-elasticsearch/security#330]
Hi,
am am new to open distro. 
I have installed open distro 1.3.0 via debian packages.

I followed the [set up a read-only role in kibana](https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/users-roles/#set-up-a-read-only-role-in-kibana) but the role to role mapping does not work.

Like the example says 

> Map kibana_user and kibana_read_only roles to the read_only_index role:

![image](https://user-images.githubusercontent.com/8988747/77730389-fd49bb00-7000-11ea-91c1-a2c05268c1c7.png)

It seems not to be mapped. 
**If I assign kibana_read_only and kibana_user directly to the user it work's.** 
Is there anything else todo what I missed?
Regards 
Nico

**Comment by dinusX** [comment]
Hi, 

I think the following sentence is confusing and needs to be rewritten
> Map kibana_user and kibana_read_only roles to the read_only_index role:

This section basically tells that you should map your user to 3 roles "kibana_user", "kibana_read_only" and "read_only_index".
Looking at your screenshot it seems that the "read_only_index" is used as user instead of role, which is not what documentation intended to say.

So, check again the steps and create first a role "read_only_index" which is supposed to give "read_only" permissions to one or more indices.

Once you have that role, assuming that you already have create a user, go to "Role Mappings" page and map your user to all 3 roles. 
The "kibana_user" role gives permissions to use "kibana" and "kibana_read_only" will restrict permissions to "read_only" (meaning that user won't be able to create "kibana" visualizations or "dashboards").
Depending on your use-case, you might want to use only "kibana_user" role instead.

Let me know if this helped, or if have any further questions.

**Comment by aetter** [comment]
Oof, thanks for the heads-up. Fixed here: https://github.com/opendistro/for-elasticsearch-docs/commit/5bdabb91b1c88d010a57049cc4e47626d89f1f15
