### ISSUE TITLE
Is it possible to use Security Plugin without SSL Transport enabled?

### ISSUE THREAD

**Issue by abhijithshivaswamy** [opendistro-for-elasticsearch/security#36]
Hi, we would like to know , if we can use the Security plugin without Transport SSL enabled?
I agree, SSL/TLS encryption is necessary for complete data security, but our application ES is for log analysis and metrics, and we run it on AWS in a VPC, with no external access to the cluster. 
We have no need of Node-to-Node encryption, but we do need the role based access, permissions feature, even though it is in reality pseudo-secure. 

Right now, i can only disable HTTPS, but cannot disable Transport SSL. I came accross this piece of code in OpenDistroSecurityPlugin.java

```
if(!transportSSLEnabled) {
            throw new IllegalStateException(SSLConfigConstants.OPENDISTRO_SECURITY_SSL_TRANSPORT_ENABLED+" must be set to 'true'");
}
```

1. Does it effectively mean, **Transport SSL needs to be turned on to use Security plugin** ?

2. Is there any reason to have this compulsion with the plugin? If so, could you please tell me.

3. Is it possible to allow the flexibility to disable Transport SSL(9300), just like how we can disable HTTPS (9200 port).

Looking forward for your response.

**Comment by hardik-k-shah** [comment]
1)  Does it effectively mean, Transport SSL needs to be turned on to use Security plugin ?
Yes, that is correct. Transport SSL must be turned on to use security plugin.

 2)  Is there any reason to have this compulsion with the plugin? If so, could you please tell me.
Inter node request carries user context (which contains sensitive information like user credential details, roles etc..), hence for securing user's sensitive information we need to enable node to node encryption.  

 3) Is it possible to allow the flexibility to disable Transport SSL(9300), just like how we can disable HTTPS (9200 port).
As of now this flexibility is not there due to security requirement.

**Comment by tantra35** [comment]
@hardik-k-shah Please correct me if i miss something. If we closing eyes on potential security issues that you described, and simply remove

```
        if(!transportSSLEnabled) {
            throw new IllegalStateException(SSLConfigConstants.OPENDISTRO_SECURITY_SSL_TRANSPORT_ENABLED+" must be set to 'true'");
        }
```

and then rebuild plugin manually, we got behavior that @abhijithshivaswamy describes, so we can disable TLS for transport protocol, and can run all fuatures that security plugin provides?

**Comment by NickDatLe** [comment]
> @hardik-k-shah Please correct me if i miss something. If we closing eyes on potential security issues that you described, and simply remove
> 
> ```
>         if(!transportSSLEnabled) {
>             throw new IllegalStateException(SSLConfigConstants.OPENDISTRO_SECURITY_SSL_TRANSPORT_ENABLED+" must be set to 'true'");
>         }
> ```
> 
> and then rebuild plugin manually, we got behavior that @abhijithshivaswamy describes, so we can disable TLS for transport protocol, and can run all fuatures that security plugin provides?

Can someone confirm this? I'm very interested in turning off inter-node TLS.

**Comment by hardik-k-shah** [comment]
Duplicate of https://github.com/opendistro-for-elasticsearch/security/issues/37
