### ISSUE TITLE
 Protocol TLSv1.3 is not supported for OpenDistro 0.9

### ISSUE THREAD

**Issue by hardik-k-shah** [opendistro-for-elasticsearch/security#415]
OpenDistro 0.9 throws an error of unsupported TLS version 1.3 if installed version of OpenSSL is less than 1.1.1.

this issue was reported by @MichelZ on [OpenDistro forum](https://discuss.opendistrocommunity.dev/t/issue-with-kibana-elasticsearch-tlsv1-3-protocol-tlsv1-3-is-not-supported/634)

[OpenSSL added support for TLSv1.3 from version 1.1.1 onwards.  ](https://wiki.openssl.org/index.php/TLS1.3).

**Comment by sujithvm** [comment]
This is fixed by https://github.com/opendistro-for-elasticsearch/deprecated-security-ssl/pull/10 
and changes are imported in opendistro-0.9 branch https://github.com/opendistro-for-elasticsearch/security/blob/opendistro-0.9/src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/DefaultOpenDistroSecurityKeyStore.java#L760
