### ISSUE TITLE
Disable username and Password authentication in Elasticsearch for client Logstash

### ISSUE THREAD

**Issue by ashuagrawalml** [opendistro-for-elasticsearch/security#466]
Hi I only want to use Mutual TLS authetication between Logstash, kibana  process and Elasticsearch instances. I want to disable basic_internal_auth_domain and other authentication for Logstash, kibana instances since i dont want to maintain password at Logstash and Kibana configuration files.

However for Kibana users doing login through kibana ui. i want to use i need to use  LDAPS based authentication.
Please let me know if its feasible to only use mTLS between Logstash,kibana processes and Elasticsearch instance. However i want to use LDAPS for kibana users.

**Comment by hardik-k-shah** [comment]
Hi @ashuagrawalml 

Yes, you can disable basic auth  and use TLS auth for Logstash and LDAP based auth for other users. 

You can control internal_user database through this settings: 
https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/config.yml#L101

And TLS auth can be controlled by: https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/config.yml#L138 

LDAP based auth can be controlled by: https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/config.yml#L150

TLS auth should also work for Kibana to Elasticsearch instances. 

1. You have to configure your kibana via kibana.yml to use client cert and a key.
2. You also need to configure TLS auth in config.yml  https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/config.yml#L138 
3. You should restrict access based on TLS cert DN name and set permission only specify by [kibana_server](https://github.com/opendistro-for-elasticsearch/security/blob/master/src/main/resources/static_config/static_roles.yml#L77) role ) . Scoped down permission can be achieved by mapping kibana cert DN to kibana_server role. 

 
PS: Kibana may not start without username ```elasticsearch.username``` in kibana.yml . But it will not be in effect if you have disabled internal_user database auth and successfully set up TLS based auth.

**Comment by ashuagrawalml** [comment]
Thanks Hardik. I will look into the configuration you suggested. I will try them in my Poc opendistro instance and let you know the outcome.

**Comment by ashuagrawalml** [comment]
Hi Hardik,
I have a quick query on your point 3 mentioned in your reply as below. 
By  TLS cert DN name were you referring to Common Name (CN)? I tried CN however it didnt worked for me. I might be missing something. Please let me know if its possible to call you?
Thanks,
Ashutosh

**Comment by debjanibnrj** [comment]
Hi @ashuagrawalml,

Thanks for your question. As @hardik-k-shah  mentioned, to enable TLS auth you need to configure it as mentioned here https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/config.yml#L138. 

This config file has a line - 
```
          config:
            username_attribute: cn #optional, if omitted DN becomes username
```

This means that when you're authenticating using TLS the CN of your certificate becomes the username. (If no username_attribute is mentioned your DN becomes the username). 

In order to obtain the CN you can execute the following command - 
`openssl x509 -noout -subject -in <your_cert_file>`

You will get an output like - 
`subject= /CN=example`

In opendistro we will use `example` as the username. The user (`example`) needs to be mapped to the `kibana_server` role in order to restrict access to kibana. 

In addition to this the certificate you're using for TLS auth must be trusted by one of the root CAs in the truststore of your nodes. 

Hope this helps. Let us know if you still run into any issues.

**Comment by ashuagrawalml** [comment]
Thanks @debjanibnrj.
One more basic query. Can i configure my own TLS certificate in AWS ES? Else does this feature is available in only opendistro ES and not in AWS ES? I believe AWS ES internally uses Opendistro ES. However i did not found the placeholders in AWS ES where in can change TLS certificates.

**Comment by debjanibnrj** [comment]
Hi @ashuagrawalml, You can't change the TLS Certificates for AWS ES as that is managed by AWS. 

You can do this with Opendistro ES though.

**Comment by ashuagrawalml** [comment]
Thanks @debjanibnrj . Looks i can't use LDAPS & AD authentication in AWS ES as well? LDAPS and AD authentication is available in Opendistro ES though. Please let me know? The authentication mechanism available to me in AWS ES looks Cognito only?

**Comment by debjanibnrj** [comment]
You're right. Right now AWS ES cannot use LDAPS & AD auth. As of now in AWS ES there is support for basic auth, IAM auth and Cognito-based auth.
