### ISSUE TITLE
Update is not supported when FLS or DLS or Fieldmasking is activated

### ISSUE THREAD

**Issue by Atreus-Technologies** [opendistro-for-elasticsearch/security#503]
Can someone please confirm whether the document update api (`/_update` endpoint) is available when DLS is enabled? 

Attempting to perform a document update on 1.8.0 appears to result in a `500` error with the message `Update is not supported when FLS or DLS or Fieldmasking is activated` (as per the title) but this limitation is not documented anywhere.

This seems like a pretty critical oversight given that it breaks existing client functionality with a relatively small configuration change to the security plugin. Are there any plans to  add support for document updates when DLS is turned on? It doesn't seem like a complex piece of functionality.

In either event, it certainly seems like something that should be documented so that users can avoid this configuration if it will cause issues with their existing functionality.

**Comment by vrozov** [comment]
It is indeed currently not supported.

**Comment by aetter** [comment]
Hi @vrozov, do you know our reasoning here? Is it that Painless could potentially allow you to bypass those security features and update a document/field that you don't have access to?

**Comment by vrozov** [comment]
I can't say for sure why it was implemented this way. My guess is that update behavior may not be well defined when FLS/DLS is present.

**Comment by chrousto** [comment]
Hello all,
I am also running into this issue that in my case is related to #13 : 

Because I want admins with all_access (no set DLS) to be able to see all documents regarding of filtering, I have used the workaround mentioned in #13 ([here](https://github.com/opendistro-for-elasticsearch/security/issues/13#issuecomment-561373938)) : 
I have created a role with a match_all query DLS. As a consequence, when an admin attempts to create an index pattern and Kibana attempts to update the default index pattern in the settings it issues an update query to the .kibana index.

Because of the fact that the _update/<id> endpoint is not available when DLS is activated ([mentioned here in the doc)](https://opendistro.github.io/for-elasticsearch-docs/docs/troubleshoot/)  I receive the mentioned error :

**Request**:
```
POST /.kibana/_update/config%3A7.10.0?refresh=wait_for&_source_includes=namespace%2Cnamespaces%2CoriginId HTTP/1.1
user-agent: elasticsearch-js/7.10.0-rc.1 (linux 3.10.0-1160.15.2.el7.x86_64-x64; Node.js v10.22.1)
x-elastic-product-origin: kibana
x-opaque-id: ***
securitytenant: __user__
authorization: Bearer ***
content-type: application/json
content-length: 79
Host: localhost:9200
Connection: keep-alive

{"doc":{"config":{"defaultIndex":"d"},"updated_at":"2021-02-26T10:48:21.279Z"}}
```

**Response** : 
```
{"error":{"root_cause":[{"type":"security_exception","reason":"Update is not supported when FLS or DLS or Fieldmasking is activated"}],"type":"security_
exception","reason":"Update is not supported when FLS or DLS or Fieldmasking is activated"},"status":500}
```

Similarly, users with DLS enabled but that can create index patterns for themselves receive an error as well, has anyone come up with a workaround for this or is it planned to look into it ? 

Kibana then displays this error : 
![image](https://user-images.githubusercontent.com/21685818/109291942-ecfe1980-7829-11eb-9d4f-3299ae187179.png)

Thanks in advance !
Christophe.

**Comment by hardik-k-shah** [comment]
@Atreus-Technologies / @aetter / @chrousto 


Update is not allowed when DLS/FLS is enabled due to security reasons and underlying implementation. There is a security risk, if documents are updated with a role that has dls, fls or field masking enabled. 

When FLS is enabled, user will be only able to see the fields that the role is permitted to see. 
If user (with FLS restricted role) try to update the existing document, he/she will be updating document without noticing those fields which are not visible to the user . And user can accidentally remove all other fields (which are not allowed to see or update) from the document. 


When DLS is enabled, user will be only able to see certain documents that the role is permitted to see. 
So, user (with DLS restricted role) is not allowed to access a specific document,  Security plugin marks it deleted on lucene level while reading those. In this case a user can potentially index a new document with the same id (with different fields / field values) and overwriting the document the user is not allowed to see.

And hence, we do not support update when DLS/FLS is enabled.

**Comment by chrousto** [comment]
Hello @hardik-k-shah and thanks for your andwer.

- I fully agree with the issue regarding FLS.
- I have a hard time understanding the issue when it comes to DLS : why would you not be allowed to update a document to which you have access for update actions ? Of course if the update targets a restricted document, the user should not be able to update it but if this is an existing document, there is no risk of creating a new one with a separate id because the document already exists. Indeed, the _update endpoint is dedicated a specific document designated by its _id (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html). As a consequence there is no risk of replacing an existing document. There are two situations in my opinion : 
  - Either the user is allowed to read and update the document and it's not marked as deleted by the Security plugin and the user can update it
  - Either the user can not access it and it can not update it either (the user does not know its _id anyway)

May be I am mistaken, what do you think ?

Thanks in advance.
Christophe

**Comment by stockholmux** [comment]
@hardik-k-shah Your description makes logical sense, although I think it's probably counter to many user's expectation.

@aetter Is what @hardik-k-shah is describing documented? Glancing through the docs for document-, field-level security and field masking I don't see anything. It's strange enough to be a big source of misunderstanding.

**Comment by aetter** [comment]
Yeah, it's in the troubleshooting section.

**Comment by stockholmux** [comment]
@aetter Ok. [I see it now](https://opendistro.github.io/for-elasticsearch-docs/docs/troubleshoot/).

Would it make sense to have this as a part of FLS, DLS and masking directly documentation (or at least link to the troubleshooting section)? I didn't find it when I looked, so that's a good litmus that others wouldn't find it either.

Also the abbreviations in the on the troubleshooting section (FLS, DLS) might prevent someone from finding it with the document search.
